import React, { useState } from 'react'
import { Image, Video, FileText, Download, Trash2, Search, Filter } from 'lucide-react'

interface MediaItem {
  id: string
  type: 'image' | 'video' | 'document'
  title: string
  url: string
  thumbnail?: string
  size: number
  createdAt: number
  conversationId?: string
  conversationTitle?: string
}

export default function LibraryPage() {
  const [mediaItems, setMediaItems] = useState<MediaItem[]>([]) // Initially empty as requested
  const [searchQuery, setSearchQuery] = useState('')
  const [filterType, setFilterType] = useState<'all' | 'image' | 'video' | 'document'>('all')
  const [selectedItems, setSelectedItems] = useState<Set<string>>(new Set())

  // Filter and search media items
  const filteredItems = mediaItems.filter(item => {
    const matchesSearch = item.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
                         item.conversationTitle?.toLowerCase().includes(searchQuery.toLowerCase())
    const matchesFilter = filterType === 'all' || item.type === filterType
    return matchesSearch && matchesFilter
  })

  // Format file size
  const formatFileSize = (bytes: number) => {
    if (bytes === 0) return '0 Bytes'
    const k = 1024
    const sizes = ['Bytes', 'KB', 'MB', 'GB']
    const i = Math.floor(Math.log(bytes) / Math.log(k))
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]
  }

  // Format date
  const formatDate = (timestamp: number) => {
    const date = new Date(timestamp)
    return date.toLocaleDateString([], { 
      year: 'numeric', 
      month: 'short', 
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })
  }

  // Handle item selection
  const toggleSelection = (itemId: string) => {
    setSelectedItems(prev => {
      const newSet = new Set(prev)
      if (newSet.has(itemId)) {
        newSet.delete(itemId)
      } else {
        newSet.add(itemId)
      }
      return newSet
    })
  }

  // Handle download
  const handleDownload = (item: MediaItem) => {
    const link = document.createElement('a')
    link.href = item.url
    link.download = item.title
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  // Handle delete
  const handleDelete = (itemId: string) => {
    if (window.confirm('Are you sure you want to delete this item?')) {
      setMediaItems(prev => prev.filter(item => item.id !== itemId))
      setSelectedItems(prev => {
        const newSet = new Set(prev)
        newSet.delete(itemId)
        return newSet
      })
    }
  }

  // Handle bulk delete
  const handleBulkDelete = () => {
    if (selectedItems.size === 0) return
    if (window.confirm(`Are you sure you want to delete ${selectedItems.size} item(s)?`)) {
      setMediaItems(prev => prev.filter(item => !selectedItems.has(item.id)))
      setSelectedItems(new Set())
    }
  }

  return (
    <div className="h-full flex flex-col" style={{ backgroundColor: '#ffffeb' }}>
      {/* Header */}
      <div className="p-6 border-b" style={{ borderColor: '#E1C28B' }}>
        <div className="flex items-center justify-between mb-4">
          <div>
            <h1 className="text-2xl font-semibold" style={{ color: '#4C3D1E' }}>
              Library
            </h1>
            <p className="text-sm mt-1" style={{ color: '#4C3D1E', opacity: 0.7 }}>
              All media generated by Chatty models
            </p>
          </div>
          
          {selectedItems.size > 0 && (
            <button
              onClick={handleBulkDelete}
              className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-colors"
              style={{ 
                backgroundColor: '#E1C28B', 
                color: '#4C3D1E' 
              }}
              onMouseEnter={(e) => e.currentTarget.style.backgroundColor = '#d4b078'}
              onMouseLeave={(e) => e.currentTarget.style.backgroundColor = '#E1C28B'}
            >
              <Trash2 size={16} />
              Delete ({selectedItems.size})
            </button>
          )}
        </div>

        {/* Search and Filter */}
        <div className="flex items-center gap-4">
          <div className="flex-1 relative">
            <Search size={16} className="absolute left-3 top-1/2 transform -translate-y-1/2" style={{ color: '#4C3D1E', opacity: 0.5 }} />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search media..."
              className="w-full pl-10 pr-4 py-2 rounded-lg border text-sm"
              style={{ 
                backgroundColor: '#ffffd7',
                borderColor: '#E1C28B',
                color: '#4C3D1E'
              }}
            />
          </div>
          
          <div className="flex items-center gap-2">
            <Filter size={16} style={{ color: '#4C3D1E', opacity: 0.7 }} />
            <select
              value={filterType}
              onChange={(e) => setFilterType(e.target.value as any)}
              className="px-3 py-2 rounded-lg border text-sm"
              style={{ 
                backgroundColor: '#ffffd7',
                borderColor: '#E1C28B',
                color: '#4C3D1E'
              }}
            >
              <option value="all">All Types</option>
              <option value="image">Images</option>
              <option value="video">Videos</option>
              <option value="document">Documents</option>
            </select>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 p-6 overflow-y-auto">
        {mediaItems.length === 0 ? (
          // Empty state
          <div className="flex flex-col items-center justify-center h-full text-center">
            <div className="w-24 h-24 rounded-full flex items-center justify-center mb-6" style={{ backgroundColor: '#feffaf' }}>
              <Image size={32} style={{ color: '#4C3D1E', opacity: 0.6 }} />
            </div>
            <h3 className="text-lg font-medium mb-2" style={{ color: '#4C3D1E' }}>
              No media yet
            </h3>
            <p className="text-sm max-w-md" style={{ color: '#4C3D1E', opacity: 0.7 }}>
              When Chatty generates images, videos, or documents for you, they'll appear here in your library.
            </p>
          </div>
        ) : filteredItems.length === 0 ? (
          // No search results
          <div className="flex flex-col items-center justify-center h-full text-center">
            <Search size={48} style={{ color: '#4C3D1E', opacity: 0.3 }} className="mb-4" />
            <h3 className="text-lg font-medium mb-2" style={{ color: '#4C3D1E' }}>
              No results found
            </h3>
            <p className="text-sm" style={{ color: '#4C3D1E', opacity: 0.7 }}>
              Try adjusting your search or filter criteria.
            </p>
          </div>
        ) : (
          // Media grid
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {filteredItems.map((item) => (
              <div
                key={item.id}
                className={`relative group rounded-lg border overflow-hidden transition-all cursor-pointer ${
                  selectedItems.has(item.id) ? 'ring-2' : ''
                }`}
                style={{ 
                  backgroundColor: '#ffffd7',
                  borderColor: selectedItems.has(item.id) ? '#4C3D1E' : '#E1C28B'
                }}
                onClick={() => toggleSelection(item.id)}
              >
                {/* Selection checkbox */}
                <div className="absolute top-2 left-2 z-10">
                  <input
                    type="checkbox"
                    checked={selectedItems.has(item.id)}
                    onChange={() => toggleSelection(item.id)}
                    className="w-4 h-4 rounded border-2"
                    style={{ 
                      backgroundColor: selectedItems.has(item.id) ? '#4C3D1E' : 'transparent',
                      borderColor: '#4C3D1E'
                    }}
                    onClick={(e) => e.stopPropagation()}
                  />
                </div>

                {/* Media preview */}
                <div className="aspect-square bg-gray-100 flex items-center justify-center">
                  {item.type === 'image' ? (
                    <Image size={32} style={{ color: '#4C3D1E', opacity: 0.5 }} />
                  ) : item.type === 'video' ? (
                    <Video size={32} style={{ color: '#4C3D1E', opacity: 0.5 }} />
                  ) : (
                    <FileText size={32} style={{ color: '#4C3D1E', opacity: 0.5 }} />
                  )}
                </div>

                {/* Item info */}
                <div className="p-3">
                  <h4 className="text-sm font-medium truncate mb-1" style={{ color: '#4C3D1E' }}>
                    {item.title}
                  </h4>
                  <p className="text-xs mb-2" style={{ color: '#4C3D1E', opacity: 0.6 }}>
                    {formatFileSize(item.size)} • {formatDate(item.createdAt)}
                  </p>
                  {item.conversationTitle && (
                    <p className="text-xs truncate" style={{ color: '#4C3D1E', opacity: 0.5 }}>
                      From: {item.conversationTitle}
                    </p>
                  )}
                </div>

                {/* Action buttons */}
                <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity">
                  <div className="flex gap-1">
                    <button
                      onClick={(e) => {
                        e.stopPropagation()
                        handleDownload(item)
                      }}
                      className="p-1 rounded bg-white shadow-sm"
                      style={{ color: '#4C3D1E' }}
                    >
                      <Download size={14} />
                    </button>
                    <button
                      onClick={(e) => {
                        e.stopPropagation()
                        handleDelete(item.id)
                      }}
                      className="p-1 rounded bg-white shadow-sm"
                      style={{ color: '#4C3D1E' }}
                    >
                      <Trash2 size={14} />
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}

