export enum OP {
  HELLO = 1,
  FILE_UPLOADED = 2,
  IDLE_TIMEOUT = 3,
  INTENT_QA = 4,
  INTENT_CODE = 5,
  INTENT_SUMMARY = 6,
  AUTH_SUCCESS = 7,
  // Large File Intelligence Layer
  FILE_CHUNKING_START = 8,
  FILE_CHUNKING_PROGRESS = 9,
  FILE_CHUNKING_COMPLETE = 10,
  FILE_INDEXING_START = 11,
  FILE_INDEXING_PROGRESS = 12,
  FILE_INDEXING_COMPLETE = 13,
  CONTEXT_QUERY_START = 14,
  CONTEXT_QUERY_PROGRESS = 15,
  CONTEXT_QUERY_COMPLETE = 16,
  SEMANTIC_SEARCH_START = 17,
  SEMANTIC_SEARCH_PROGRESS = 18,
  SEMANTIC_SEARCH_COMPLETE = 19,
  VECTOR_STORE_READY = 20,
  // Memory and Continuity System
  MEMORY_CREATED = 21,
  MEMORY_UPDATED = 22,
  MEMORY_DELETED = 23,
  MEMORY_RETRIEVED = 24,
  MEMORY_INJECTED = 25,
  CONTINUITY_HOOK_CREATED = 26,
  CONTINUITY_HOOK_TRIGGERED = 27,
  SESSION_MEMORY_LOADED = 28,
  USER_MEMORY_SYNCED = 29,
  MEMORY_RITUAL_COMPLETED = 30,
  // Symbolic Reasoning System
  SYMBOLIC_PATTERN_DETECTED = 31,
  MOTIF_SYNTHESIZED = 32,
  THEME_INFERRED = 33,
  SYMBOLIC_QUERY_EXECUTED = 34,
  ANCHOR_PATTERN_FOUND = 35,
  RECURSIVE_MOTIF_TRACKED = 36,
  SYMBOLIC_REASONING_COMPLETED = 37,
  THEMATIC_ANALYSIS_FINISHED = 38,
  PATTERN_CORRELATION_DISCOVERED = 39,
  SYMBOLIC_INSIGHT_GENERATED = 40,
  // Narrative Synthesis System
  NARRATIVE_SYNTHESIZED = 41,
  STORYLINE_GENERATED = 42,
  NARRATIVE_QUERY_EXECUTED = 43,
  MULTI_DOCUMENT_SYNTHESIS_COMPLETED = 44,
  NARRATIVE_SCAFFOLDING_CREATED = 45,
  SYMBOLIC_FRAMING_APPLIED = 46,
  NARRATIVE_CONTINUITY_ESTABLISHED = 47,
  STORY_ARC_DETECTED = 48,
  NARRATIVE_INSIGHT_GENERATED = 49,
  NARRATIVE_SYNTHESIS_COMPLETED = 50,
  ERROR = 255
}

export type Packet = {
  op: OP;            // opcode
  ts: number;        // unix ms
  uid?: string;      // user id
  cid?: string;      // conversation id
  payload?: Uint8Array; // binary payload (CBOR)
};
