#!/bin/bash

echo "🌐 Cloudflare Account Setup Guide"
echo "================================="
echo ""
echo "The free trycloudflare.com service is currently experiencing issues."
echo "Here's how to set up a proper Cloudflare tunnel:"
echo ""
echo "1. 📝 Create a free Cloudflare account:"
echo "   → Go to https://dash.cloudflare.com/sign-up"
echo "   → Sign up with your email"
echo ""
echo "2. 🔑 Get your Account ID:"
echo "   → Go to https://dash.cloudflare.com/"
echo "   → Copy your Account ID from the right sidebar"
echo ""
echo "3. 🚀 Create a tunnel:"
echo "   → Run: cloudflared tunnel login"
echo "   → Run: cloudflared tunnel create chatty-tunnel"
echo "   → Run: cloudflared tunnel route dns chatty-tunnel chatty.yourdomain.com"
echo ""
echo "4. ⚙️  Configure the tunnel:"
echo "   → Edit ~/.cloudflared/config.yml"
echo "   → Add your tunnel configuration"
echo ""
echo "5. 🏃 Start the tunnel:"
echo "   → Run: cloudflared tunnel run chatty-tunnel"
echo ""
echo "📚 Full documentation: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/"
echo ""
echo "Would you like me to help you with any of these steps?"
